CREATE SCHEMA EXERCISE1;
CREATE TABLE EMP_1 

(EMP_NUM CHAR(3),
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3));

INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('1', 'David', 'Dwight Matthew', 'G', '2023-03-28', '601');
INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('2', 'Miembro', 'Charles Simon', 'G', '2023-03-28', '602');

SELECT * FROM exercise1.emp_1
WHERE JOB_CODE = '602';